#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PrivateChat.Resource", IsApplication=true)]

namespace PrivateChat
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::com.refractored.fab.Resource.Attribute.fab_colorDisabled = global::PrivateChat.Resource.Attribute.fab_colorDisabled;
			global::com.refractored.fab.Resource.Attribute.fab_colorNormal = global::PrivateChat.Resource.Attribute.fab_colorNormal;
			global::com.refractored.fab.Resource.Attribute.fab_colorPressed = global::PrivateChat.Resource.Attribute.fab_colorPressed;
			global::com.refractored.fab.Resource.Attribute.fab_colorRipple = global::PrivateChat.Resource.Attribute.fab_colorRipple;
			global::com.refractored.fab.Resource.Attribute.fab_shadow = global::PrivateChat.Resource.Attribute.fab_shadow;
			global::com.refractored.fab.Resource.Attribute.fab_size = global::PrivateChat.Resource.Attribute.fab_size;
			global::com.refractored.fab.Resource.Color.fab_material_blue_500 = global::PrivateChat.Resource.Color.fab_material_blue_500;
			global::com.refractored.fab.Resource.Dimension.fab_elevation_lollipop = global::PrivateChat.Resource.Dimension.fab_elevation_lollipop;
			global::com.refractored.fab.Resource.Dimension.fab_scroll_threshold = global::PrivateChat.Resource.Dimension.fab_scroll_threshold;
			global::com.refractored.fab.Resource.Dimension.fab_shadow_size = global::PrivateChat.Resource.Dimension.fab_shadow_size;
			global::com.refractored.fab.Resource.Dimension.fab_size_mini = global::PrivateChat.Resource.Dimension.fab_size_mini;
			global::com.refractored.fab.Resource.Dimension.fab_size_normal = global::PrivateChat.Resource.Dimension.fab_size_normal;
			global::com.refractored.fab.Resource.Drawable.fab_shadow = global::PrivateChat.Resource.Drawable.fab_shadow;
			global::com.refractored.fab.Resource.Drawable.fab_shadow_mini = global::PrivateChat.Resource.Drawable.fab_shadow_mini;
			global::com.refractored.fab.Resource.Id.mini = global::PrivateChat.Resource.Id.mini;
			global::com.refractored.fab.Resource.Id.normal = global::PrivateChat.Resource.Id.normal;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton = global::PrivateChat.Resource.Styleable.FloatingActionButton;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorDisabled = global::PrivateChat.Resource.Styleable.FloatingActionButton_fab_colorDisabled;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorNormal = global::PrivateChat.Resource.Styleable.FloatingActionButton_fab_colorNormal;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorPressed = global::PrivateChat.Resource.Styleable.FloatingActionButton_fab_colorPressed;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorRipple = global::PrivateChat.Resource.Styleable.FloatingActionButton_fab_colorRipple;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_shadow = global::PrivateChat.Resource.Styleable.FloatingActionButton_fab_shadow;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_size = global::PrivateChat.Resource.Styleable.FloatingActionButton_fab_size;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int fab_colorDisabled = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int fab_colorNormal = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int fab_colorPressed = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int fab_colorRipple = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int fab_shadow = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int fab_size = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int blue = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int fab_material_blue_500 = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int gray = 2130968578;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050004
			public const int fab_elevation_lollipop = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int fab_scroll_threshold = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int fab_shadow_size = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int fab_size_mini = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int fab_size_normal = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int fab_shadow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int fab_shadow_mini = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_add = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int roundButton = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int splash = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090005
			public const int GroupName = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int LastMessage = 2131296262;
			
			// aapt resource value: 0x7f090008
			public const int LastTimeStamp = 2131296264;
			
			// aapt resource value: 0x7f090026
			public const int Title = 2131296294;
			
			// aapt resource value: 0x7f090007
			public const int TotalMessages = 2131296263;
			
			// aapt resource value: 0x7f090018
			public const int Tv1 = 2131296280;
			
			// aapt resource value: 0x7f090019
			public const int Tv2 = 2131296281;
			
			// aapt resource value: 0x7f09001a
			public const int Tv3 = 2131296282;
			
			// aapt resource value: 0x7f090029
			public const int actionDelete = 2131296297;
			
			// aapt resource value: 0x7f090027
			public const int actionDeleteConversation = 2131296295;
			
			// aapt resource value: 0x7f090028
			public const int actionEdit = 2131296296;
			
			// aapt resource value: 0x7f090004
			public const int cfab = 2131296260;
			
			// aapt resource value: 0x7f090003
			public const int conversationList = 2131296259;
			
			// aapt resource value: 0x7f09000a
			public const int fab = 2131296266;
			
			// aapt resource value: 0x7f09001e
			public const int infoTv1 = 2131296286;
			
			// aapt resource value: 0x7f09001f
			public const int infoTv2 = 2131296287;
			
			// aapt resource value: 0x7f090017
			public const int ipAddress1 = 2131296279;
			
			// aapt resource value: 0x7f090016
			public const int ipAddress2 = 2131296278;
			
			// aapt resource value: 0x7f090015
			public const int ipAddress3 = 2131296277;
			
			// aapt resource value: 0x7f090014
			public const int ipAddress4 = 2131296276;
			
			// aapt resource value: 0x7f090011
			public const int ipAddressTv = 2131296273;
			
			// aapt resource value: 0x7f090023
			public const int itemIPAddress = 2131296291;
			
			// aapt resource value: 0x7f090025
			public const int itemPortNumber = 2131296293;
			
			// aapt resource value: 0x7f090022
			public const int itemServerName = 2131296290;
			
			// aapt resource value: 0x7f090024
			public const int itemTv = 2131296292;
			
			// aapt resource value: 0x7f09000e
			public const int messageEt = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int messagesList = 2131296271;
			
			// aapt resource value: 0x7f090000
			public const int mini = 2131296256;
			
			// aapt resource value: 0x7f090013
			public const int name = 2131296275;
			
			// aapt resource value: 0x7f090010
			public const int nameTv = 2131296272;
			
			// aapt resource value: 0x7f090001
			public const int normal = 2131296257;
			
			// aapt resource value: 0x7f090020
			public const int phoneEt = 2131296288;
			
			// aapt resource value: 0x7f09001b
			public const int portNumber = 2131296283;
			
			// aapt resource value: 0x7f090012
			public const int portNumberTv = 2131296274;
			
			// aapt resource value: 0x7f090002
			public const int relativeLayout1 = 2131296258;
			
			// aapt resource value: 0x7f090021
			public const int saveBtn = 2131296289;
			
			// aapt resource value: 0x7f09000d
			public const int sendBtn = 2131296269;
			
			// aapt resource value: 0x7f09000c
			public const int sendToEt = 2131296268;
			
			// aapt resource value: 0x7f090009
			public const int serverList = 2131296265;
			
			// aapt resource value: 0x7f09001d
			public const int titleSpace = 2131296285;
			
			// aapt resource value: 0x7f09001c
			public const int titleTv = 2131296284;
			
			// aapt resource value: 0x7f09000b
			public const int toTv = 2131296267;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Conversation = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ConversationListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Messages = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int NewServerDialog = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int registerPhone = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ServerListItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int title = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int ConversationActionBar = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int ServerActionBar = 2131230721;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070002
			public const int Light_BlueTitle = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int SplashTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int TBS = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FloatingActionButton = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 2
			public const int FloatingActionButton_fab_colorDisabled = 2;
			
			// aapt resource value: 1
			public const int FloatingActionButton_fab_colorNormal = 1;
			
			// aapt resource value: 0
			public const int FloatingActionButton_fab_colorPressed = 0;
			
			// aapt resource value: 3
			public const int FloatingActionButton_fab_colorRipple = 3;
			
			// aapt resource value: 4
			public const int FloatingActionButton_fab_shadow = 4;
			
			// aapt resource value: 5
			public const int FloatingActionButton_fab_size = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
